import type { NextPage } from 'next'
import Head from 'next/head'

const Page: NextPage<{ id: string }> = ({ id }) => {
  return (
    <>
      <Head>
        <title>project {id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:type" content='website' />
      </Head>

      <main>
        <p>pppp</p>
      </main>
    </>
  )
}

Page.getInitialProps = async (context) => {
  const { id } = context.query;

  return {
    id: id as string,
  };
}


export default Page;